# Generated by Django 5.2.6 on 2025-09-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='passwordhistory',
            old_name='changed_at',
            new_name='created_at',
        ),
    ]
