# Generated by Django 5.2.6 on 2025-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant')], max_length=20, null=True),
        ),
    ]
