# Generated by Django 5.2.6 on 2025-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registrationrequest_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='security_question_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant')], default='ACCOUNTANT', max_length=20),
        ),
    ]
