# Generated by Django 5.2.6 on 2025-10-12 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_temporary_password_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_SUSPENDED', 'User Suspended'), ('USER_UNSUSPENDED', 'User Unsuspended'), ('USER_UPDATED', 'User Updated'), ('REQUEST_APPROVED', 'Access Approved'), ('REQUEST_REJECTED', 'Access Rejected'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset')], max_length=32),
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, unique=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_description', models.TextField()),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('account_category', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('account_subcategory', models.CharField(max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('order', models.PositiveIntegerField(help_text='Display order (e.g., 01 for Cash)')),
                ('statement', models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('RE', 'Retained Earnings')], max_length=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['order', 'account_number'],
            },
        ),
    ]
