# Generated by Django 5.2.6 on 2025-10-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_eventlog_action_chartofaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='deactivate_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='deactivate_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
