# Generated by Django 5.2.6 on 2025-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_chartofaccounts_deactivate_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='after_image',
            field=models.JSONField(blank=True, help_text='State of the record after the change', null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='before_image',
            field=models.JSONField(blank=True, help_text='State of the record before the change', null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='record_id',
            field=models.IntegerField(blank=True, help_text='ID of the affected record', null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='record_type',
            field=models.CharField(blank=True, help_text='Type of record (User, Account, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_SUSPENDED', 'User Suspended'), ('USER_UNSUSPENDED', 'User Unsuspended'), ('USER_UPDATED', 'User Updated'), ('REQUEST_APPROVED', 'Access Approved'), ('REQUEST_REJECTED', 'Access Rejected'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_UPDATED', 'Account Updated'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated')], max_length=32),
        ),
    ]
