# Generated by Django 5.2.6 on 2025-10-21 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_eventlog_action_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='closure_reason',
            field=models.TextField(blank=True, help_text='Reason for closing this account'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
