# Generated by Django 5.2.6 on 2025-11-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_chartofaccounts_closed_at_chartofaccounts_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('ADJUSTED', 'Adjusted'), ('CLOSING', 'Closing')], default='REGULAR', max_length=20),
        ),
    ]
