version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - echo "Installing backend dependencies..."
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - npm run build
      - cd ..

  build:
    commands:
      - echo "Collecting static files..."
      - cd backend
      - python manage.py collectstatic --noinput || true
      - cd ..
      - echo "Build phase completed."

artifacts:
  files:
    - '**/*'
  base-directory: .
