version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - pip install -r requirements.txt
      - npm install --prefix frontend
  build:
    commands:
      # Build React frontend
      - npm run build --prefix frontend
      # Collect Django static files (so EB can serve them)
      - python manage.py collectstatic --noinput
      # Package everything into a deployable directory
      - mkdir -p deploy
      - cp -r * deploy/ || true
artifacts:
  files:
    - '**/*'
  base-directory: deploy
