version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt --log /var/log/pip_install.log
      - cat /var/log/pip_install.log
      - echo "Installing Node.js dependencies..."
      - npm ci --prefix frontend

  build:
    commands:
      - echo "Building React frontend..."
      - npm run build --prefix frontend

artifacts:
  files:
    - '**/*'
  discard-paths: no
