version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
      - echo "Installing Node.js dependencies..."
      - npm ci --prefix frontend

  build:
    commands:
      - echo "Building React frontend..."
      - npm run build --prefix frontend
      - echo "Copying build output to backend static directory..."
      - cp -r frontend/dist backend/static

artifacts:
  files:
    - backend/**/*
    - Procfile
    - .ebextensions/**/*
